# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/coco/opt/anaconda3/lib/python3.8/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/coco/opt/anaconda3/lib/python3.8/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/coco/working_directory/project_computer_vision_motion_estimation/MotionWithoutMovement

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/coco/working_directory/project_computer_vision_motion_estimation/MotionWithoutMovement

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/coco/opt/anaconda3/lib/python3.8/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/coco/opt/anaconda3/lib/python3.8/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/coco/working_directory/project_computer_vision_motion_estimation/MotionWithoutMovement/CMakeFiles /home/coco/working_directory/project_computer_vision_motion_estimation/MotionWithoutMovement//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/coco/working_directory/project_computer_vision_motion_estimation/MotionWithoutMovement/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SteerableFilter

# Build rule for target.
SteerableFilter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SteerableFilter
.PHONY : SteerableFilter

# fast build rule for target.
SteerableFilter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SteerableFilter.dir/build.make CMakeFiles/SteerableFilter.dir/build
.PHONY : SteerableFilter/fast

NewParksMcClellan.o: NewParksMcClellan.cpp.o
.PHONY : NewParksMcClellan.o

# target to build an object file
NewParksMcClellan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SteerableFilter.dir/build.make CMakeFiles/SteerableFilter.dir/NewParksMcClellan.cpp.o
.PHONY : NewParksMcClellan.cpp.o

NewParksMcClellan.i: NewParksMcClellan.cpp.i
.PHONY : NewParksMcClellan.i

# target to preprocess a source file
NewParksMcClellan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SteerableFilter.dir/build.make CMakeFiles/SteerableFilter.dir/NewParksMcClellan.cpp.i
.PHONY : NewParksMcClellan.cpp.i

NewParksMcClellan.s: NewParksMcClellan.cpp.s
.PHONY : NewParksMcClellan.s

# target to generate assembly for a file
NewParksMcClellan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SteerableFilter.dir/build.make CMakeFiles/SteerableFilter.dir/NewParksMcClellan.cpp.s
.PHONY : NewParksMcClellan.cpp.s

iirfilter.o: iirfilter.cpp.o
.PHONY : iirfilter.o

# target to build an object file
iirfilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SteerableFilter.dir/build.make CMakeFiles/SteerableFilter.dir/iirfilter.cpp.o
.PHONY : iirfilter.cpp.o

iirfilter.i: iirfilter.cpp.i
.PHONY : iirfilter.i

# target to preprocess a source file
iirfilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SteerableFilter.dir/build.make CMakeFiles/SteerableFilter.dir/iirfilter.cpp.i
.PHONY : iirfilter.cpp.i

iirfilter.s: iirfilter.cpp.s
.PHONY : iirfilter.s

# target to generate assembly for a file
iirfilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SteerableFilter.dir/build.make CMakeFiles/SteerableFilter.dir/iirfilter.cpp.s
.PHONY : iirfilter.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SteerableFilter.dir/build.make CMakeFiles/SteerableFilter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SteerableFilter.dir/build.make CMakeFiles/SteerableFilter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SteerableFilter.dir/build.make CMakeFiles/SteerableFilter.dir/main.cpp.s
.PHONY : main.cpp.s

pyramid.o: pyramid.cpp.o
.PHONY : pyramid.o

# target to build an object file
pyramid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SteerableFilter.dir/build.make CMakeFiles/SteerableFilter.dir/pyramid.cpp.o
.PHONY : pyramid.cpp.o

pyramid.i: pyramid.cpp.i
.PHONY : pyramid.i

# target to preprocess a source file
pyramid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SteerableFilter.dir/build.make CMakeFiles/SteerableFilter.dir/pyramid.cpp.i
.PHONY : pyramid.cpp.i

pyramid.s: pyramid.cpp.s
.PHONY : pyramid.s

# target to generate assembly for a file
pyramid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SteerableFilter.dir/build.make CMakeFiles/SteerableFilter.dir/pyramid.cpp.s
.PHONY : pyramid.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SteerableFilter"
	@echo "... NewParksMcClellan.o"
	@echo "... NewParksMcClellan.i"
	@echo "... NewParksMcClellan.s"
	@echo "... iirfilter.o"
	@echo "... iirfilter.i"
	@echo "... iirfilter.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pyramid.o"
	@echo "... pyramid.i"
	@echo "... pyramid.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

